CREATE TABLE IF NOT EXISTS `study_notes` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `study_id` VARCHAR(64) NOT NULL,
    `note` TEXT NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_study_id` (`study_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
